name: vadrigar

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 3

  qlds:
    image: qlds:latest
    container_name: qlds
    stdin_open: true
    tty: true
    stop_grace_period: 0s
    ports:
      - "27960:27960/udp"
      - "27960:27960/tcp"
    volumes:
      - ./volumes/data:/data:rw
      - ./volumes/qlds/steamapps:/qlds/steamapps:rw
      - ./volumes/qlds/homepath:/qlds/homepath:rw
      - ./volumes/qlds/minqlx-plugins:/qlds/minqlx-plugins:rw
      - ./volumes/qlds/baseq3/server.cfg:/qlds/baseq3/server.cfg:rw
      - ./volumes/qlds/baseq3/scripts:/qlds/baseq3/scripts:rw
      - ./volumes/qlds/baseq3/workshop.txt:/qlds/baseq3/workshop.txt:rw
      - ./volumes/qlds/baseq3/mappool_ca_vamp.txt:/qlds/baseq3/mappool.txt:rw
    environment:
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.qlds
    # develop:
    #   watch:
    #     - path: ./Dockerfile.qlds
    #       action: rebuild
    #     - path: ./volumes/minqlx-plugins
    #       action: sync+restart
    #       target: /mnt/data/minqlx-plugins
